#!/bin/bash

F=`find . -name "CMakeCache.txt" -o -name "CMakeFiles" -o -name "cmake_install.cmake"`
echo $F
rm -rf $F

F=`find . -name "*.o" -o -name "*.ko" -o -name "*.o.d" -o -name "*.syms"`
echo $F
rm -f $F
