#!/bin/bash

function usage() {
	echo "Usage: `basename $0` <search> <replaces> files..."
	echo 1
}

if [ $# -lt 2 ]; then
	usage
fi

SEARCH=$1; shift
REPLACE=$1; shift

echo "sed -i s/$SEARCH/$REPLACE/g" "$@" > /dev/stderr
if [ $# -gt 0 ]; then
	sed -i "s/$SEARCH/$REPLACE/g" "$@"
else
	sed -e "s/$SEARCH/$REPLACE/g"
fi
