#!/bin/bash

TARGET=artik10
PROF=tizen
ARCH=armv7l

GBS_ROOT=~/GBS-ROOT/${PROF}/local
KEYMAN_ROOT=~/sec-os/key-manager
BUILD_ROOT=${GBS_ROOT}/BUILD-ROOTS/scratch.${ARCH}.0
BUILD_RPMS=${GBS_ROOT}/repos/${PROF}/${ARCH}/RPMS

sudo cp ${KEYMAN_ROOT}/tests/ca-km.cpp ${BUILD_ROOT}/home
sudo cp ${KEYMAN_ROOT}/tests/make-cakm.sh ${BUILD_ROOT}/home
sudo chmod +x ${BUILD_ROOT}/home ${KEYMAN_ROOT}/tests/make-cakm.sh
