#!/bin/bash

TARGET=artik10
PROF=tizen
ARCH=armv7l

GBS_ROOT=~/GBS-ROOT/${PROF}/local
BUILD_ROOT=${GBS_ROOT}/BUILD-ROOTS/scratch.${ARCH}.0
BUILD_RPMS=${GBS_ROOT}/repos/${PROF}/${ARCH}/RPMS

sdb root on
echo "Copying files to target..."
rm -rf /tmp/install-km
mkdir -p /tmp/install-km
cp "${BUILD_RPMS}/key-manager-0.1.23-1.${ARCH}.rpm" /tmp/install-km/
cp "${BUILD_RPMS}/libkey-manager-common-0.1.23-1.${ARCH}.rpm" /tmp/install-km/
cp "${BUILD_RPMS}/libkey-manager-client-0.1.23-1.${ARCH}.rpm" /tmp/install-km/
cp "${BUILD_RPMS}/key-manager-pam-plugin-0.1.23-1.${ARCH}.rpm" /tmp/install-km/
#cp "${BUILD_RPMS}/security-tests-0.0.45-1.${ARCH}.rpm" /tmp/install-km/
#cp "${BUILD_RPMS}/key-manager-tests-0.1.23-1.${ARCH}.rpm" /tmp/install-km/

cat > /tmp/install-km/init.sh <<EOF
ip link set eth0 up
ip addr add 172.16.0.60/24 dev eth0
insmod /tzdev.ko
tzdaemon
EOF

cat > /tmp/install-km/poc-key-manager-tz.sh <<EOF
echo "Seting up..."
lsmod|grep tzdev || insmod /tzdev.ko
ps ax|grep -v grep|grep tzdaemon || tzdaemon
echo "done"

echo "Running native secos CA talking with TA (GP)"
/usr/apps/ca_km
echo "=============================================="
echo

echo "Running user app talking to key-manager with TZ backend (TA over GP)"
/root/ca-km
echo "=============================================="
echo
EOF
chmod +x /tmp/install-km/poc-key-manager-tz.sh

sdb shell "rm -f /tmp/*.rpm"
sdb push /tmp/install-km/init.sh /root
sdb push /tmp/install-km/poc-key-manager-tz.sh /
sdb push /tmp/install-km/*.rpm /tmp
# only CA/TA are updated
sdb push ${BUILD_ROOT}/home/ca-km /root/
sdb push ${BUILD_ROOT}/usr/apps/ca_km /usr/apps/
sdb push ${BUILD_ROOT}/usr/apps/tee/*666666555555 /usr/apps/tee/
#sdb push "${BUILD_ROOT}/usr/bin/tzdaemon" /usr/bin
#sdb push "${BUILD_ROOT}/lib/modules/tzdev.ko" /lib/modules
#sdb push "${BUILD_ROOT}/usr/lib/libteec.so" /usr/lib/

echo "installing rpm(s)..."
sdb shell "cd /tmp && rpm -U --nodeps --force *.rpm"
#echo "rpm -U --force --nodeps key-manager-tests-0.1.23-1.${ARCH}.rpm"
#sdb shell "cd /tmp && rpm -U --force --nodeps key-manager-tests-0.1.23-1.${ARCH}.rpm"
