#!/bin/bash

TARGET=artik10
PROF=tizen
ARCH=armv7l

BUILD_ROOT=~/sec-os/secosci/.build/build-${TARGET}
GBS_ROOT=~/GBS-ROOT/${PROF}/local/BUILD-ROOTS/scratch.${ARCH}.0
SRC_ROOT=~/sec-os/secos

echo "Installing ..."
sudo mkdir -p ${GBS_ROOT}/usr/apps/tee
sudo cp ${BUILD_ROOT}/app-ree-install/usr/apps/* ${GBS_ROOT}/usr/apps/
echo "  ${BUILD_ROOT}/app-tee-install/usr/apps/tee/* => ${GBS_ROOT}/usr/apps/tee"
sudo cp ${BUILD_ROOT}/app-tee-install/usr/apps/tee/* ${GBS_ROOT}/usr/apps/tee

echo "  ${BUILD_ROOT}/ree-install/modules/tzdev.ko => ${GBS_ROOT}/lib/modules"
sudo cp ${BUILD_ROOT}/ree-install/modules/tzdev.ko ${GBS_ROOT}/lib/modules
echo "  ${BUILD_ROOT}/ree-install/bin/tzdaemon => ${GBS_ROOT}/usr/bin"
sudo cp ${BUILD_ROOT}/ree-install/bin/tzdaemon ${GBS_ROOT}/usr/bin
echo "  ${BUILD_ROOT}/ree-install/lib/libteec.so => ${GBS_ROOT}/usr/lib/"
sudo cp ${BUILD_ROOT}/ree-install/lib/libteec.so ${GBS_ROOT}/usr/lib/
echo "  ${BUILD_ROOT}/ree-install/include/*.h => ${GBS_ROOT}/include/"
sudo cp ${BUILD_ROOT}/ree-install/include/*.h ${GBS_ROOT}/usr/include/
echo "done."
