#!/bin/bash

DEV="/dev/ttyUSB0"

while [ $# -gt 0 ]; do
    a="$1"; shift
	case "$a" in
		/dev/*) DEV=$a ;;
		[0-9]) DEV="/dev/ttyUSB$a" ;;
		usb*)  DEV="/dev/tty"`echo $a|tr '[:lower:]' '[:upper:]'` ;;
		USB*)  DEV="/dev/tty$a" ;;
		ttyS*) DEV="/dev/"`echo $a|tr '[:lower:]' '[:upper:]'` ;;
		S*) DEV="/dev/tty"`echo $a|tr '[:lower:]' '[:upper:]'` ;;
	esac
done

NAME=`basename $DEV`

sudo minicom -w -c on -D $DEV -C "/VolGroup02/tmp/${NAME}-capture.txt"
